config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: redirect('/courses')

  ActiveAdmin.routes(self)

  resources :courses, only: %i[index show]

  post :group_member, to: 'group_members#create'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  has_many :groups, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  accepts_nested_attributes_for :groups, allow_destroy: true
end

app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  just_define_datetime_picker :start_at

  belongs_to :course

  has_many :group_students, dependent: :destroy
  has_many :students, through: :group_students

  validates :start_at, presence: true, uniqueness: { scope: :course_id }

  default_scope { order(:start_at) }

  scope :active, -> { where('start_at > ?', DateTime.current) }
end

app/models/group_student.rb
# frozen_string_literal: true

class GroupStudent < ApplicationRecord
  belongs_to :group
  belongs_to :student
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  has_many :group_students, dependent: :destroy
  has_many :groups, through: :group_students

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: ENV['SELF_USERNAME'], password: ENV['SELF_PASSWORD'], if: :admin_controller?

  def admin_controller?
    self.class < ActiveAdmin::BaseController
  end
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  breadcrumb I18n.t('courses'), :courses_path

  def index
    @grid = CoursesGrid.new(courses_grid_params) do |scope|
      scope.page(params[:page])
    end
  end

  def show
    breadcrumb course.name, course_path(course.id)

    @groups = course.groups.active.includes(:students).order(:start_at)
  end

  private

  def courses_grid_params
    @courses_grid_params ||= params.fetch(:courses_grid, {}).permit!
  end

  def course
    @course ||= Course.find(params[:id])
  end
end

app/controllers/group_members_controller.rb
# frozen_string_literal: true

class GroupMembersController < ApplicationController
  def create
    @group_member = GroupMemberForm.new(group_member_params)

    if @group_member.save
      render status: :ok
    else
      render(:create_failed)
    end
  end

  private

  def group_member_params
    @group_member_params ||= params.require(:group_member_form).permit(:group_id, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/courses/index.html.slim
= datagrid_table @grid
= paginate(@grid.assets)

app/views/courses/show.html.slim
- @groups.each do |group|
  div id="group_#{group.id}"
    = render(partial: 'courses/show/group', locals: { group: group })

app/views/courses/show/_group.html.slim
- group_member_form ||= GroupMemberForm.new

div
  p #{I18n.t('study_start_at')}: #{group.start_at.strftime('%d.%m.%Y %H:%M')}
  div
    p #{I18n.t('students')}:
    ul
      - group.students.each do |student|
        li #{student.email}
  = render(partial: 'courses/show/register_form', locals: { group: group, group_member_form: group_member_form })    
  hr

app/views/courses/show/_register_form.html.slim
= form_for group_member_form, url: group_member_path, method: :create, remote: true do |f|
  = f.hidden_field :group_id, value: group.id

  div
    = f.label :email
    = f.text_field :email

  - if group_member_form.errors.present?
    p Не удалось записаться:
    ul
    - group_member_form.errors.full_messages.each do |error|
      li #{error}

  div
    = submit_tag I18n.t('assign')

app/views/group_members/create.js.erb
document.querySelector("#group_<%= @group_member.group_id %>").innerHTML = "<%= j render(partial: 'courses/show/group', locals: { group: @group_member.group }) %>"

app/views/group_members/create_failed.js.erb
document.querySelector("#group_<%= @group_member.group_id %>").innerHTML = "<%= j render(partial: 'courses/show/group', locals: { group: @group_member.group, group_member_form: @group_member }) %>"

app/views/layouts/_breadcrumbs.html.slim
div
  - breadcrumb_trail do |crumb|
    - if crumb.current?
      a = crumb.name
    - else
      = link_to(crumb.name, crumb.url)
      span = ' / '

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MailJob
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render(partial: 'layouts/breadcrumbs')
    = yield